---
env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  camelcase:
    - error
  comma-dangle:
    - error
  eol-last:
    - warn
    - always
  max-len:
    - error
    { "ignoreComments": true, "ignoreTrailingComments": true }
  no-var:
    - error
...